# Generated by Django 4.2.6 on 2024-05-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ushop", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_image", models.ImageField(upload_to="uploads/product/")),
                (
                    "product_desc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_price", models.IntegerField()),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ushop.category"
                    ),
                ),
            ],
        ),
    ]
